### PR TITLE
Restore support for sources on v1 api

### PR DESCRIPTION
**Pull request by elupus**
This moves data request on v5/6 api into the channel functions instead
which seems more in line with what they actually do. Once
https://github.com/home-assistant/home-assistant/pull/15941 is
merged the source list should just return a single entry for
v5 api (or be corrected to actually grab list of sources)

### CODE REVIEW

**Comment by elupus** [comment]
@yottatsa could you check that this still works on v5/6 api?

**Comment by danielperna84** [comment]
Since I can't test I guess we'll wait until @yottatsa responds. 🤔

**Comment by yottatsa** [comment]
Will test today

**Comment by zjuanma** [comment]
When do you merge this pull request? I have a TV with V1 Api, and this PR is needed.
Thanks.

**Comment by danielperna84** [comment]
We're still waiting for @yottatsa to verify that this doesn't break API 5/6. I myself can't do this since I don't have any devices.

**Comment by yottatsa** [comment]
It's failing on v5/6 API. Will check

```
>>> tv = haphilipsjs.PhilipsTV('192.168.1.6', '6')
>>> tv.update()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/homeassistant/venv/lib/python3.5/site-packages/haphilipsjs/__init__.py", line 67, in update
    self.getSources()
  File "/home/homeassistant/venv/lib/python3.5/site-packages/haphilipsjs/__init__.py", line 144, in getSources
    return self.getChannels()
  File "/home/homeassistant/venv/lib/python3.5/site-packages/haphilipsjs/__init__.py", line 98, in getChannels
    self.channels.extend(r.get('Channel', []))
AttributeError: 'NoneType' object has no attribute 'extend'
```

**Comment by elupus** [comment]
Right. Needs self.channels initialized to an empty list.

**Comment by yottatsa** [comment]
@elupus testing with 
```
     def getChannels(self):
         if self.api_version >= '5':
+            self.channels = []
             for channelListId in self.getChannelLists():

```

**Comment by yottatsa** [comment]
Trying to unblock https://github.com/home-assistant/home-assistant/pull/15941 in the Discord in order to get that.

Also, bugs with sources/channels: testing code https://github.com/yottatsa/ha-philipsjs/commit/29058216b27ef5041dbc9643641d9aeb5aa300cb, output https://gist.github.com/yottatsa/de6d5d890a11454efcb8ec65fa0741d2

**Comment by elupus** [comment]
Ok. I'll look it over when I get a chance.

**Comment by yottatsa** [comment]
@elupus here, I've untangled both APIs https://gist.github.com/yottatsa/03bf720a53644e73b09914fbd7829e08, https://github.com/yottatsa/ha-philipsjs/commit/5fb68fa50ed8c66ecedf14fc363f8df32e22756f.  Could you please test that it works with v1? If yes, I'll create a PR on top of yours.

**Comment by thrust15** [comment]
@yottatsa I've tested your code on the v1fixes branch with my V1

first I got 

```
INFO:__main__:Source: HDMI 1
Traceback (most recent call last):
  File "__main__.py", line 34, in <module>
    for srcid in tv.sources[:10]
TypeError: unhashable type: 'slice'
```

I changed the last line of the traceback in your `__main__.py` to:
`for srcid in tv.sources` (minus the `[:10]`)

Then my results were:
```
INFO:__main__:Source: HDMI 1
INFO:__main__:Sources: Watch TV, HDMI 1, HDMI 2, HDMI 3, HDMI Side, EXT 1, Y Pb Pr, VGAi...
Traceback (most recent call last):
  File "__main__.py", line 37, in <module>
    logger.info('Channel: %s', tv.getChannelName(tv.channel_id))
  File "/home/nik/.local/lib/python3.6/site-packages/haphilipsjs/__init__.py", line 123, in getChannelName
    return self.channels.get(ccid, dict()).get('name', None)
AttributeError: 'NoneType' object has no attribute 'get'
```
Which is not really weird as I don't have channels configured on my tv, but the sources are returned correctly IMO

Response on /1/channels/ 😄 
```
{

}
```

**Comment by yottatsa** [comment]
Thnx, I'll return to you tmrw

**Comment by elupus** [comment]
@yottatsa did you get around to creating the updated pull?

**Comment by elupus** [comment]
@danielperna84 think we should be good to go. Here. Once this is in pypi I can submit a pull to homeassistant.

**Comment by danielperna84** [comment]
Could you resolve the conflicts please so I can merge without breaking anything?

**Comment by elupus** [comment]
Ouch. Missed that. Will fix tomorrow.

**Comment by elupus** [comment]
There we go

**Comment by danielperna84** [comment]
I have released [0.0.6](https://pypi.org/project/ha-philipsjs/0.0.6/) on pypi. You may test this and take care of the integration in Home Assistant now. 👍

**Comment by thrust15** [comment]
I’ve installed 0.0.6 and sources are available in home assistant for my v1 tv 🎉

**Comment by danielperna84** [comment]
Now it would be nice to see if we have any regression on newer models, or if for those functionality remains as it was until now. 😉

**Comment by elupus** [comment]
I'll combine channels and sources for my pull on Hass. So hopefully it
won't. :)

Den tors 11 apr. 2019 21:54Daniel Perna <notifications@github.com> skrev:

**Pull request merged**
