### PR TITLE
If channel does not exist try to remove prefix

### PR DESCRIPTION
**Pull request by guilherme-santos**

### CODE REVIEW

**Comment by elupus** [comment]
Could you give me the raw data where this is needed?

**Comment by guilherme-santos** [comment]
Sure...

```sh
curl http://192.168.0.19:1925/1/channels/current
```
```json
{
	"id": "4_524417"
}
```

But the actual channel id is `524417`

**Comment by elupus** [comment]
Can you check the favorite channel lists?

**Comment by guilherme-santos** [comment]
I didn't have any favorite channel so far, I just created one:

```sh
curl http://192.168.0.19:1925/1/channellists
{
	"0": {
		"name": "All TV channels",
		"source": "tv"
	},
	"1": {
		"name": "Favourite TV channels",
		"source": "tv"
	}
}
```

Or is there any other way to check the favorite channel lists?

**Comment by elupus** [comment]
And what is the data in http://192.168.0.19:1925/1/channellists/0 and in 
http://192.168.0.19:1925/1/channellists/1?

**Comment by guilherme-santos** [comment]
```
curl http://192.168.0.19:1925/1/channellists/0
[
"0_262273",
"0_524417",
"0_786561",
"0_1048705",
"0_1310849",
"0_1572993",
"0_1835137",
"0_2097281",
"0_2359425",
...
]
```
* No 4_* if that what you’re looking for

```
curl http://192.168.0.19:1925/1/channellists/1
[
"1_262273",
"1_524417"
]
```

**Comment by elupus** [comment]
And the channelist/4?

**Comment by guilherme-santos** [comment]
Mmh, good question...

This is the case for 2 and 3
```
curl http://192.168.0.19:1925/1/channellists/2
[
"2_@"
]
```

This is the case for 4+
```
curl http://192.168.0.19:1925/1/channellists/4
[
"@"
]
```

**Comment by elupus** [comment]
Strangeness. How does your channels look? Also what device is this?

**Comment by elupus** [comment]
It does seem to prefix with some identifier for tv state (ie how it reached that place)

**Comment by guilherme-santos** [comment]
My TV model is 43PUS6201/12

```bash
curl http://192.168.0.19:1925/1/channels
{
"262273": {
"preset": "1",
"name": "Das Erste HD"
},
"524417": {
"preset": "2",
"name": "ZDF HD"
},
"786561": {
"preset": "3",
"name": "NDR FS HH HD"
},
"1048705": {
"preset": "4",
"name": "SAT.1"
},
"1310849": {
"preset": "5",
"name": "RTL"
},
"1572993": {
"preset": "6",
"name": "RTLZWEI"
},
...
}
```

**Comment by elupus** [comment]
Can you adjust the test for this special case?

**Comment by guilherme-santos** [comment]
I couldn't make to run the test in my machine. Could you check?

**Comment by elupus** [comment]
Test worked fine.

**Pull request merged**
