### PR TITLE
Improve support for version 6 API

### PR DESCRIPTION
**Pull request by yottatsa**
This is based on 50PUS6272/05 API 6.1.0 nettvversion 4.6.0

* TV has a browser inside, which is exposed via activity
* if there are no channels, handle empty `channeldb/tv` for version 6
* handle non-existent/empty `channeldb/tv/channelLists/alltv` for version 5
* returns channel numbers if names are not set

### CODE REVIEW

**Comment by danielperna84** [comment]
Looking good. Any chance you want to become the owner/maintainer of this project? I don't have a Philips TV anymore, and I don't like the idea of mergings PRs I can't test. 👼

**Comment by yottatsa** [comment]
Sure thing. I will ask teammates as well if they have any Philips.

I reckon kind of test-suite that could lookup a TV in the network with upnp, and then could try to run some scenarios and collect responses.

**Comment by jacdominguez** [comment]
It works like a charm, I have it tested with a 65PUS6162/12 API 6, I finally have all the feedback from my TV and I even can select the channel I want.  I love you guys!!. Thank you both for your effort

**Comment by danielperna84** [comment]
Does this require changes to the platform in HASS? I have published the new version on PyPI, so this can be integrated into HASS now.

**Comment by jacdominguez** [comment]
I saw that the philips tv component is asking for ha-philipsjs tag 0.0.4 specifically so yes, they have to update it and point it to your 0.0.5 tag

**Comment by danielperna84** [comment]
I know that. It's my platform code after all. 😉  What I mean is if there are any logical changes besides upgrading the version of the dependency. Or are the changes reverse compatible?

**Comment by yottatsa** [comment]
@jacdominguez could you please try to install https://github.com/yottatsa/ha-philipsjs/commit/58a628c97bcf3c7396de190b96b048172895909b and run `python -m haphilipsjs`.

I want to build proper tests so I'm collecting test data now.

**Comment by danielperna84** [comment]
@yottatsa 

Do you have a PyPi account? I would add you as a maintainer or even owner if you want to. Makes it easier for you to publish new releases.
I have also created a PR for HASS that references the new version. So for now everything is done.

**Comment by elupus** [comment]
I might want to have a look at this too. Getting channel list working now that HA soon have support for having a list of channels too.

**Pull request merged**
